//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIB_BASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_BOIS
    {
        public int ID_BOIS { get; set; }
        public string Nom { get; set; }
        public string Origine { get; set; }
    }
}
